### ISSUE TITLE
Bug: YamlDotNet serialization/deserialization exception

### ISSUE THREAD

**Issue by cdavernas** [neuroglia-io/AsyncApi#8]
## How to reproduce?

Add a new operation using a single value type parameter to an AsyncApiDocument, and try serializing it to Yaml.

## Expected behavior

The AsyncApiDocument is correctly serialized.

## Actual behavior

The [YamlDotNetSerializer](https://github.com/neuroglia-io/framework/blob/main/src/Serialization/Neuroglia.Serialization.YamlDotNet/YamlDotNetSerializer.cs) fails to serialize the `AsyncApiDocument`, because of the automatically generated example for the added operation. 
As a matter of fact, when using a single value type parameter, the generated example is a simple `JToken`, as opposed to being a `JObject`. 
Here's the exception thrown in such cases (reproduced by visiting https://localhost:44326/asyncapi/TemperatureSensorApi/1.0.0 on the solution's sample app) :
```
YamlException: (Line: 1, Col: 1, Idx: 0) - (Line: 1, Col: 1, Idx: 0): Expected SCALAR, SEQUENCE-START, MAPPING-START, or ALIAS, got MappingEnd
```

## Additonal info

The exception is doubtlessly caused by the [JTokenSerializer](https://github.com/neuroglia-io/framework/blob/main/src/Serialization/Neuroglia.Serialization.YamlDotNet/Converters/JTokenSerializer.cs)

**Comment by abbottdev** [comment]
I'm getting a serialization exception when attempting to build a AsyncApi document, my issue appears to be when trying to serialize a "Definition" - which the Yaml converter thinks is a URI (as it's a pointer within the document.) - This throws a "Object must implement IConvertible" error, which is misleading.

**Comment by cdavernas** [comment]
@abbottdev I just published a new release today, with updated package references. Can you confirm that your issue has been resolved?
P.S: don't forget to check and play with the agnostic AsyncAPI client I just added ;)

**Comment by Breate** [comment]
Still not working. i recieve next error :

`YamlDotNet.Core.YamlException: (Line: 1, Col: 1, Idx: 0) - (Line: 1, Col: 1, Idx: 0): Expected SCALAR, SEQUENCE-START, MAPPING-START, or ALIAS, got MappingEnd
         at YamlDotNet.Core.Emitter.EmitNode(ParsingEvent evt, Boolean isMapping, Boolean isSimpleKey)
         at YamlDotNet.Core.Emitter.Emit(ParsingEvent event)
         at YamlDotNet.Serialization.EventEmitters.WriterEventEmitter.YamlDotNet.Serialization.IEventEmitter.Emit(MappingEndEventInfo eventInfo, IEmitter emitter)
         at YamlDotNet.Serialization.EventEmitters.ChainedEventEmitter.Emit(MappingEndEventInfo eventInfo, IEmitter emitter)
         at YamlDotNet.Serialization.ObjectGraphVisitors.EmittingObjectGraphVisitor.YamlDotNet.Serialization.IObjectGraphVisitor<YamlDotNet.Core.IEmitter>.VisitMappingEnd(IObjectDescriptor mapping, IEmitter context)
         at YamlDotNet.Serialization.ObjectGraphTraversalStrategies.FullObjectGraphTraversalStrategy.TraverseDictionary[TContext](IObjectDescriptor dictionary, IObjectGraphVisitor`1 visitor, Type keyType, Type valueType, TContext context, Stack`1 path)
`
